### ISSUE TITLE
Ion / Rust string incompatibility

### ISSUE THREAD

**Issue by mlanghinrichs** [PeytonT/serde_ion#1]
Should users be required to explicitly pass an IonString type in order to serialize it, or should serialization simply fail on invalid rust strings?

**Comment by PeytonT** [comment]
The Ion data model for string should be compatible with Rust's UTF8 Strings since the data model represents unicode codepoints but is not opinionated on the encoding.

http://amzn.github.io/ion-docs/docs/stringclob.html
https://doc.rust-lang.org/std/string/struct.String.html
