### ISSUE TITLE
Ion Text Parser

### ISSUE THREAD

**Issue by siler** [PeytonT/serde_ion#10]
Hey all,

I've been putting some work in on an Ion text parser via Nom 5 in my spare time. It's to the point where it is pretty solid, I think, though I haven't started any benchmarking. I'm still failing some tests but they are related to integration with a symbol table implementation, but it looks like there's been some progress on that. Anywho, if ya'll are interested I'll throw up a PR. It's pretty big at around 1.8k loc for the parser proper (though some of that is early symbol table validation) and 2.2k for the test suite.

**Comment by PeytonT** [comment]
Hi there,

Great to hear! I'd be happy to see that PR, though fair warning that I'm in the middle of a refactoring effort to bring the crate more in line with the conventions in [serde_json](https://github.com/serde-rs/json/blob/master/src/value/mod.rs), particularly in the ion_types module. The biggest changes are a shift to using equivalent idiomatic Rust ecosystem types where possible, and a transition to using Options to represent typed nulls.

This is also a spare-time project on my end, so my attention has been sporadic. I was planning once I wrapped up binary ser/de to build the text ser/de integration using [pest](https://pest.rs/), but based on their benchmarks it looks like a reasonable Nom-based parser is likely to be more performant.
