### ISSUE TITLE
How should typed nulls be deserialized?

### ISSUE THREAD

**Issue by mlanghinrichs** [PeytonT/serde_ion#2]
For instance, in the case of null.string, should we use Option<String> with None representing the null case? How could we represent bare null as opposed to null.null?

See #7 for the inverse issue.

**Comment by PeytonT** [comment]
In src/ion_types.rs I've gone with the solution of modeling the Ion data model as a collection of enums inhabited by structs. This is similar to the approach taken by serde_json.

https://docs.serde.rs/serde_json/value/enum.Value.html
