### ISSUE TITLE
Canonical ion vs. format preservation

### ISSUE THREAD

**Issue by mlanghinrichs** [PeytonT/serde_ion#3]
We're leaning towards a "canonical ion" IR which guarantees equality between input and output, but not identical formatting. How could we offer format preservation in the future? Should we?

**Comment by PeytonT** [comment]
I think we can make the decision now to never support format preservation, or at least to be clear that it's not on the roadmap for any specific timescale. I think what is on the roadmap long-term is support for the ability to deserialize to a specific optional representation, i.e. deserialize all IonIntegers into hex and all IonDecimals to use a capital 'D'. This can be handled down the road by exposing a second set of deserialization functions that take a formatting struct.
