### ISSUE TITLE
Find open-source Ion files for examples and testing

### ISSUE THREAD

**Issue by mlanghinrichs** [PeytonT/serde_ion#5]
Look into Java and Python Ion implementations?

**Comment by mlanghinrichs** [comment]
Other implementations yield nothing but amazon provides files at  [ion-tests](https://github.com/amzn/ion-tests)

**Comment by PeytonT** [comment]
Glad to know that our hand-writing of Ion will be minimal, since ion-tests looks great. It's available under Apache License 2.0 and has wonderful commit messages like "adding more clob" and "Nop pad equiv examples", so I'll definitely see about pulling their tests in and organizing a test harness.

**Comment by mlanghinrichs** [comment]
Closing issue as open-source source files have been found.
