### ISSUE TITLE
Pull in ion test files and organize test harness

### ISSUE THREAD

**Issue by mlanghinrichs** [PeytonT/serde_ion#8]
Glad to know that our hand-writing of Ion will be minimal, since ion-tests looks great. It's available under Apache License 2.0 and has wonderful commit messages like "adding more clob" and "Nop pad equiv examples", so I'll definitely see about pulling their tests in and organizing a test harness.

_Originally posted by @PeytonT in https://github.com/PeytonT/serde_ion/issues/5#issuecomment-480692205_

**Comment by PeytonT** [comment]
Addressed in [b865672ebba6afdce8481e3d6a0276353199cefb](https://github.com/PeytonT/serde_ion/commit/b865672ebba6afdce8481e3d6a0276353199cefb) and again in [276f1ae37e3e4ef8196099a8a49f6bb7a58c5cd9](https://github.com/PeytonT/serde_ion/commit/276f1ae37e3e4ef8196099a8a49f6bb7a58c5cd9).
